src/TKE/Models/Dolgozo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TKE.Models
{
    public class Dolgozo
    {
        [ScaffoldColumn(false)]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public int DolgozoID { get; set; }

        [Required(ErrorMessage = "Név megadása kötelező!")]
        [Display(Name = "Dolgozó név")]
        [MaxLength(45)]
        public string DolgozoNev { get; set; }

        [Required(ErrorMessage = "Azonosító megadása kötelező!")]
        [Display(Name = "Azonosító")]
        [MaxLength(45)]
        public string Azonosito { get; set; }

        [Required(ErrorMessage = "Jelszó megadása kötelező!")]
        [Display(Name = "Jelszó")]
        [DataType(DataType.Password)]
        [ConcurrencyCheck, MaxLength(45, ErrorMessage = "A jelszónak 6 és 45 karakter között kell lennie"), MinLength(6)]
        public string Jelszo { get; set; }

        [Required(ErrorMessage = "Jogultsági szint megadása kötelező!")]
        [Display(Name = "Jogosultság")]
        [MaxLength(1)]
        public string Szint { get; set; }

        [Required]
        [Display(Name = "Óradíj hétközben")]
        [DefaultValue(0)]
        public int OraHK { get; set; }

        [Required]
        [Display(Name = "Óradíj hétvégén")]
        [DefaultValue(0)]
        public int OraHV { get; set; }

        [Required]
        [Display(Name = "Kilométer szorzó")]
        [DefaultValue(0)]
        public int KmSzorzo { get; set; }

    }
}

src/TKE/ViewModels/Account/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TKE.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

src/TKE/ViewModels/Dolgozo/BejelentkezesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TKE.ViewModels.Dolgozo
{
    public class BejelentkezesViewModel
    {
        [Required]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        public string Azonosito { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Jelszo { get; set; }
    }
}

src/TKE/Controllers/DolgozoController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using TKE.Models;
using TKE.Services;
using TKE.ViewModels.Dolgozo;


namespace TKE.Controllers
{
    public class DolgozoController : Controller
    {
        private ApplicationDbContext _context;

        public DolgozoController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Dolgozo
        public IActionResult Index()
        {
            return View(_context.Dolgozo.ToList());
        }

        // GET: Dolgozo/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Dolgozo dolgozo = _context.Dolgozo.Single(m => m.DolgozoID == id);
            if (dolgozo == null)
            {
                return HttpNotFound();
            }

            return View(dolgozo);
        }

        // GET: Dolgozo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dolgozo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Dolgozo dolgozo)
        {
            if (ModelState.IsValid)
            {
                _context.Dolgozo.Add(dolgozo);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dolgozo);
        }

        // GET: Dolgozo/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Dolgozo dolgozo = _context.Dolgozo.Single(m => m.DolgozoID == id);
            if (dolgozo == null)
            {
                return HttpNotFound();
            }
            return View(dolgozo);
        }

        // POST: Dolgozo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Dolgozo dolgozo)
        {
            if (ModelState.IsValid)
            {
                _context.Update(dolgozo);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dolgozo);
        }

        // GET: Dolgozo/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Dolgozo dolgozo = _context.Dolgozo.Single(m => m.DolgozoID == id);
            if (dolgozo == null)
            {
                return HttpNotFound();
            }

            return View(dolgozo);
        }

        // POST: Dolgozo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Dolgozo dolgozo = _context.Dolgozo.Single(m => m.DolgozoID == id);
            _context.Dolgozo.Remove(dolgozo);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TKE/Views/Dolgozo/Create.cshtml
@model TKE.Models.Dolgozo

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Dolgozo</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Azonosito" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Azonosito" class="form-control" />
                <span asp-validation-for="Azonosito" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DolgozoNev" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DolgozoNev" class="form-control" />
                <span asp-validation-for="DolgozoNev" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Jelszo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Jelszo" class="form-control" />
                <span asp-validation-for="Jelszo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="KmSzorzo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="KmSzorzo" class="form-control" />
                <span asp-validation-for="KmSzorzo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OraHK" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OraHK" class="form-control" />
                <span asp-validation-for="OraHK" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OraHV" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OraHV" class="form-control" />
                <span asp-validation-for="OraHV" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Szint" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Szint" class="form-control" />
                <span asp-validation-for="Szint" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/TKE/Views/Dolgozo/Delete.cshtml
@model TKE.Models.Dolgozo

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dolgozo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Azonosito)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Azonosito)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DolgozoNev)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DolgozoNev)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Jelszo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Jelszo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KmSzorzo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KmSzorzo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OraHK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OraHK)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OraHV)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OraHV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Szint)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Szint)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/TKE/Views/Dolgozo/Details.cshtml
@model TKE.Models.Dolgozo

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Dolgozo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Azonosito)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Azonosito)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dolgozo_nev)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dolgozo_nev)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Jelszo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Jelszo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Km_Szorzo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Km_Szorzo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ora_HK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ora_HK)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ora_HV)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ora_HV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Szint)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Szint)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/TKE/Views/Dolgozo/Edit.cshtml
@model TKE.Models.Dolgozo

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Dolgozo</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Azonosito" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Azonosito" class="form-control" />
                <span asp-validation-for="Azonosito" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DolgozoNev" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DolgozoNev" class="form-control" />
                <span asp-validation-for="DolgozoNev" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Jelszo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Jelszo" class="form-control" />
                <span asp-validation-for="Jelszo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="KmSzorzo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="KmSzorzo" class="form-control" />
                <span asp-validation-for="KmSzorzo" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OraHK" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OraHK" class="form-control" />
                <span asp-validation-for="OraHK" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OraHV" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="OraHV" class="form-control" />
                <span asp-validation-for="OraHV" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Szint" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Szint" class="form-control" />
                <span asp-validation-for="Szint" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/TKE/Views/Dolgozo/Index.cshtml
@using System.Collections.Generic
@using Microsoft.AspNet.Http
@using System.Security.Claims

@model IEnumerable<TKE.Models.Dolgozo>

@{
    ViewData["Title"] = "Dolgozók";
}

@if (User.IsSignedIn())
{
    <h2>Dolgozók kezelése</h2>
    <hr />
    <div class="container" style="margin-top:50px">
        <div style="margin:7px">
            <div class="col-md-6 form-group">
                <input type="text" class="form-control" placeholder="Szűrés">
            </div>
            <a asp-action="Create" class="btn btn-primary pull-right"><b>+</b> Új dolgozó felvitele</a>
        </div>
        <div class="panel-body" style="padding:0px">
            <table class="table table-striped table-bordered" style="margin:0px">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Azonosito)</th>
                        <th>@Html.DisplayNameFor(model => model.DolgozoNev)</th>
                        <th>@Html.DisplayNameFor(model => model.Szint)</th>
                        <th>@Html.DisplayNameFor(model => model.OraHK)</th>
                        <th>@Html.DisplayNameFor(model => model.OraHV)</th>
                        <th>@Html.DisplayNameFor(model => model.KmSzorzo)</th>
                        <th style="width:100px">Műveletek</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Azonosito)</td>
                            <td>@Html.DisplayFor(modelItem => item.DolgozoNev)</td>
                            <td>@Html.DisplayFor(modelItem => item.Szint)</td>
                            <td>@Html.DisplayFor(modelItem => item.OraHK)</td>
                            <td>@Html.DisplayFor(modelItem => item.OraHV)</td>
                            <td>@Html.DisplayFor(modelItem => item.KmSzorzo)</td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.DolgozoID" class="btn btn-primary btn-xs" title="Modosit"><i class="glyphicon glyphicon-pencil"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.DolgozoID" class="btn btn-danger btn-xs" title="Torol"><i class="glyphicon glyphicon-trash"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <ul class="pager">
                <li><a href="#"><i class="glyphicon glyphicon-arrow-left"></i> Előző</a></li>
                <li><a href="#">Következő <i class="glyphicon glyphicon-arrow-right"></i></a></li>
            </ul>
        </div>
    </div>
}

src/TKE/Views/Dolgozo/Login.cshtml
@using System.Collections.Generic
@using Microsoft.AspNet.Http
@using Microsoft.AspNet.Http.Authentication

@model TKE.ViewModels.Dolgozo.BejelentkezesViewModel
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Bejelentkezés";
    ViewData["ReturnUrl"] = "~/Dolgozo";
}


<h2>@ViewData["Title"]</h2>
<hr />
<div class="container">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <form asp-controller="Dolgozo" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
                <fieldset>
                    <div class="form-group input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input asp-for="Azonosito" class="form-control" placeholder="Email" />
                    </div>
                    <span asp-validation-for="Azonosito" class="text-danger"></span>
                    <div class="form-group input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input asp-for="Jelszo" class="form-control" placeholder="Jelszó" />
                    </div>
                    <span asp-validation-for="Jelszo" class="text-danger"></span>
                    <div class="form-group input-group">
                        <button type="submit" class="btn btn-primary">Belépés <i class="glyphicon glyphicon-log-in"></i></button>
                    </div>
                </fieldset>
            </form>
         </div>
    </div>
</div> <!-- /container -->


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}